// @flow

export const GET_MESSAGES_INBOX_REQUEST = 'GET_MESSAGES_INBOX_REQUEST';
export const GET_MESSAGES_INBOX_SUCCESS = 'GET_MESSAGES_INBOX_SUCCESS';
export const GET_MESSAGES_INBOX_FAILURE = 'GET_MESSAGES_INBOX_FAILURE';

export const GET_MESSAGES_SENT_REQUEST = 'GET_MESSAGES_SENT_REQUEST';
export const GET_MESSAGES_SENT_SUCCESS = 'GET_MESSAGES_SENT_SUCCESS';
export const GET_MESSAGES_SENT_FAILURE = 'GET_MESSAGES_SENT_FAILURE';

export const GET_MESSAGES_SPAM_REQUEST = 'GET_MESSAGES_SPAM_REQUEST';
export const GET_MESSAGES_SPAM_SUCCESS = 'GET_MESSAGES_SPAM_SUCCESS';
export const GET_MESSAGES_SPAM_FAILURE = 'GET_MESSAGES_SPAM_FAILURE';

export const GET_MESSAGES_TRASH_REQUEST = 'GET_MESSAGES_TRASH_REQUEST';
export const GET_MESSAGES_TRASH_SUCCESS = 'GET_MESSAGES_TRASH_SUCCESS';
export const GET_MESSAGES_TRASH_FAILURE = 'GET_MESSAGES_TRASH_FAILURE';

export const POST_MESSAGE_REQUEST = 'POST_MESSAGE_REQUEST';
export const POST_MESSAGE_SUCCESS = 'POST_MESSAGE_SUCCESS';
export const POST_MESSAGE_FAILURE = 'POST_MESSAGE_FAILURE';

export const UPDATE_MESSAGE_REQUEST = 'UPDATE_MESSAGE_REQUEST';
export const UPDATE_MESSAGE_SUCCESS = 'UPDATE_MESSAGE_SUCCESS';
export const UPDATE_MESSAGE_FAILURE = 'UPDATE_MESSAGE_FAILURE';

export const DELETE_MESSAGE_REQUEST = 'DELETE_MESSAGE_REQUEST';
export const DELETE_MESSAGE_SUCCESS = 'DELETE_MESSAGE_SUCCESS';
export const DELETE_MESSAGE_FAILURE = 'DELETE_MESSAGE_FAILURE';
